<!DOCTYPE>
<html>
	<head>
	<?php require_once 'header.php'; ?>
	<meta name="keywords" content="笑话"/>
       <meta name="descripion" content="笑话大全"/>
       <meta name="image" content="http://guweihua.yun.93me.com/logo.png">
       <title>笑话大全</title> 
	</head>
<body>
		<?php require_once 'animation.php'; ?>

		<script type="text/javascript">
		
                </script>

		<div class="row"> 
       
				<!-- Teal page content  -->		
				<div class="col s12 m8 l9">     
				</div>
				
				<div class="col s12 m4 l3">
				</div>
		</div>
</body>
</html>
