<!DOCTYPE>
<html>
	<head>
	<?php require_once 'header.php'; ?>
	<meta name="keywords" content="趣图 开心 笑话"/>
       <meta name="descripion" content="开心趣图，可以开心的可笑图片"/>
       <meta name="image" content="http://guweihua.yun.93me.com/logo.png">
       <title>开心趣图</title> 
	</head>
<body>
		<?php require_once 'animation.php'; ?>
		<?php require_once 'baidutuicong.php'; ?>

		<script type="text/javascript">
		
                </script>
		<?php require_once 'nav.php'; ?>
		<?php require_once 'headerad.php'; ?>
		<div class="container">
		<div class="row"> 
       
				<!-- Teal page content  -->		
				<div class="col s12 m10 l9">     
					<?php 
						echo '<ul>';
						foreach($pic as $item){
						echo '<li class="collection-item avatar">';
						echo        '<div class="card black-grey darken-1">';
            					echo 		'<div class="card-content black-text">';
              					echo 		'<span class="card-title">'.$item['content'].'</span>';
           					echo               '</div>';
						echo 		'<img src="'.$item['url'].' " />';	
         					echo        '</div>';

						echo "</li>";
						}
						echo "</ul>";
						
					?>
				</div>
				
				<div class="col s12 m2 l3">
					<?php require_once 'rightad.php' ; ?>
				</div>
		</div>
		</div>
		<?php require_once 'footer.php' ; ?>
</body>
</html>
