<!DOCTYPE>
<html>
	<head>
	<meta charset="utf-8" />
	 <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="public/materialize.css">
	<link href="http://cdn.bootcss.com/material-design-icons/2.2.0/iconfont/material-icons.css" rel="stylesheet">
        <!-- Compiled and minified JavaScript -->
        <script src="public/materialize.js"></script>
	</head>
<body>
		<h1>this is a test to app </h1>
		<h4>database info:</h4>
		<?php print_r($test); ?>
		<h1> member test </h1>
		<?php print_r($testmember); ?>
</body>
</html>
