<!DOCTYPE>
<html>
	<head>
	<?php require_once 'header.php'; ?>
	<meta name="keywords" content="笑话 开心"/>
       <meta name="descripion" content="开心笑话，让你开心"/>
       <meta name="image" content="http://guweihua.yun.93me.com/logo.png">
       <title>开心笑话</title> 
	</head>
<body>
		<?php require_once 'animation.php'; ?>

		<script type="text/javascript">
		
                </script>
		<?php require_once 'nav.php'; ?>
		<?php require_once 'headerad.php'; ?>
		<?php require_once 'baidutuicong.php'; ?>
		<div class="container">
		<div class="row"> 
       
				<!-- Teal page content  -->		
				<div class="col s12 m8 l9">     
					<?php 
						echo '<ul class="collection">';
						foreach($randomxiaohua as $item){
						echo '<li class="collection-item avatar">';
						echo $item['content'];
						echo "</br>";
						echo "</li>";
						}
						echo "</ul>";
						
					?>
				</div>
				
				<div class="col s12 m4 l3">
					<?php require_once 'rightad.php' ; ?>
				</div>
		</div>
		</div>
		<?php require_once 'footer.php' ; ?>
</body>
</html>
